language: r
r: 
  release

sudo: required
warnings_are_errors: true
cache: packages

# Install Ubuntu's more up to date spatial libraries
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev
      - libudunits2-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libjq-dev
      - libv8-3.14-dev
      - gdal-bin
      - libgeos++-dev

# Install development package which gissr requires
r_github_packages:
  - skgrange/threadr

